### ISSUE TITLE
Jsonnet symbol not found error

### ISSUE THREAD

**Issue by taha-au** [EmbarkStudios/k8s-buildkite-plugin#10]
**Describe the bug**

We have a pipeline where we are trying to launch an `echo "Hello World"` using this plugin. The pipeline yaml looks as follows:
```
steps:
  - command: "echo 'Hello, World!'"
    plugins:
      - EmbarkStudios/k8s#1.2.0:
          image: embarkstudios/k8s-buildkite-agent:1.2.0
```

When we launch a build on buildkite (using `buildkite-agent:3.15.0`) for that pipeline, we get the following error:
```
Error relocating /usr/lib/libjsonnet.so.0: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
error: no objects passed to apply
No resources found.
🚨 Error: The command exited with status 1
```
We used the `buildkite-agent:3.17.0` and the 

**To Reproduce**
1. Go to Buildkite
2. Add a new pipeline with the config pasted above
3. Launch a new build
4. See the error in the `Starting Kubernetes Job section`

**Expected behavior**
This is expected to create a kubernetes job to echo 'Hello, World!', and not give the strange jsonnet lib error.

**Screenshots**
![image](https://user-images.githubusercontent.com/50331398/86159763-c6d87c00-bad8-11ea-80fd-485cab52c1af.png)

**Device:**
The device is irrelevant since it's just to show the UI. Here's some info related the buildkite setup
- k8s-buildkite-agent: 1.2.0
- buildkite-agent: 3.15.0
- k8s server: v1.11.8 (irrelevant since the kubectl calls aren't the error causes)

**Additional context**
N/A
