### ISSUE TITLE
Init container failing due to Jsonnet import failure

### ISSUE THREAD

**Issue by clbx** [EmbarkStudios/k8s-buildkite-plugin#65]
**Describe the bug**
The init container bombs out during the "Start Kubernetes Job" section due to being unable to import `/tmp/job-env-<id>`

**To Reproduce**
```
steps:
  - key: k8s-build
    label: "Kubernetes Build"
    command:
    - "echo \"Hello World\""
    plugins:
    - greymatter-io/k8s:
        image: alpine:latest
        secret-name: <secret-name>
        agent-token-secret-key: <buildkite-agent-token-key>
        mount-secret: <some mounting secrets>
        git-ssh-secret-name: <secret-name>
        git-ssh-secret-key: <secret-key>
```

**Screenshots**
```
Starting Kubernetes Job | 0s
-- | --
  | RUNTIME ERROR: couldn't open import "/tmp/job-env-01865403-5c84-4531-b02f-061cd146d4362409616407": no match locally or in the Jsonnet library paths.
  | tla:stepEnvFile:1:1-73	thunk <stepEnvFile>
  | /buildkite/plugins/github-com-greymatter-io-k8s-buildkite-plugin/lib/job.jsonnet:57:26-37	thunk <str>
  | std.jsonnet:102:17-20
  | std.jsonnet:102:8-21	thunk <a>
  | std.jsonnet:102:8-33	function <anonymous>
  | std.jsonnet:102:8-33	function <anonymous>
  | /buildkite/plugins/github-com-greymatter-io-k8s-buildkite-plugin/lib/job.jsonnet:57:16-44	thunk <a>
  | /buildkite/plugins/github-com-greymatter-io-k8s-buildkite-plugin/lib/job.jsonnet:(51:5)-(59:6)	function <anonymous>
  | /buildkite/plugins/github-com-greymatter-io-k8s-buildkite-plugin/lib/job.jsonnet:(51:5)-(59:6)	thunk <stepEnv>
  | /buildkite/plugins/github-com-greymatter-io-k8s-buildkite-plugin/lib/job.jsonnet:62:5-12	thunk <podEnv>
  | /buildkite/plugins/github-com-greymatter-io-k8s-buildkite-plugin/lib/job.jsonnet:314:18-24	object <anonymous>
  | /buildkite/plugins/github-com-greymatter-io-k8s-buildkite-plugin/lib/job.jsonnet:(310:11)-(343:26)	thunk <array_element>
  | /buildkite/plugins/github-com-greymatter-io-k8s-buildkite-plugin/lib/job.jsonnet:(309:21)-(344:10)	object <anonymous>
  | /buildkite/plugins/github-com-greymatter-io-k8s-buildkite-plugin/lib/job.jsonnet:(302:13)-(350:8)	object <anonymous>
  | /buildkite/plugins/github-com-greymatter-io-k8s-buildkite-plugin/lib/job.jsonnet:(295:15)-(351:6)	object <anonymous>
  | /buildkite/plugins/github-com-greymatter-io-k8s-buildkite-plugin/lib/job.jsonnet:(290:9)-(352:4)	object <anonymous>
  | During manifestation
```

**Additional context**
- This is using [out fork](https://github.com/greymatter-io/k8s-buildkite-plugin) which is even with this repository.
- This is our first time using init images.
